# Generated by Django 4.0.3 on 2022-04-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(primary_key=10, serialize=False)),
                ('birthday', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
